name: scrape mercari
on: [push]
# on:
#   schedule:
#     - cron: "schedule:
  - cron: "* * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: create env file
        run: |
          touch .env
          echo EMAIL =${{ secrets.EMAIL }} >> .env
          echo PASSWORD =${{ secrets.PASSWORD }} >> .env
      - run: npm install
      - run: npm run start
